// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh0H32GZxy8scmwoo0_aaZvsxT53injxo',
    appId: '1:460449020290:web:120fbbe84fcd51af6df79b',
    messagingSenderId: '460449020290',
    projectId: 'codepriest-portfolio-92faf',
    authDomain: 'codepriest-portfolio-92faf.firebaseapp.com',
    storageBucket: 'codepriest-portfolio-92faf.firebasestorage.app',
    measurementId: 'G-MQS9YVH9ZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbaURYjIfHXU8PXABCgLvIGSXYdOVl1ag',
    appId: '1:460449020290:android:a470fb2019bf04376df79b',
    messagingSenderId: '460449020290',
    projectId: 'codepriest-portfolio-92faf',
    storageBucket: 'codepriest-portfolio-92faf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbIOhL66hkajrtq0dEhxpVi2nzlT-th9U',
    appId: '1:460449020290:ios:f92751d66a8b621e6df79b',
    messagingSenderId: '460449020290',
    projectId: 'codepriest-portfolio-92faf',
    storageBucket: 'codepriest-portfolio-92faf.firebasestorage.app',
    iosBundleId: 'com.nippoga.codepriestPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbIOhL66hkajrtq0dEhxpVi2nzlT-th9U',
    appId: '1:460449020290:ios:f92751d66a8b621e6df79b',
    messagingSenderId: '460449020290',
    projectId: 'codepriest-portfolio-92faf',
    storageBucket: 'codepriest-portfolio-92faf.firebasestorage.app',
    iosBundleId: 'com.nippoga.codepriestPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh0H32GZxy8scmwoo0_aaZvsxT53injxo',
    appId: '1:460449020290:web:5d9d6ed26cebe83c6df79b',
    messagingSenderId: '460449020290',
    projectId: 'codepriest-portfolio-92faf',
    authDomain: 'codepriest-portfolio-92faf.firebaseapp.com',
    storageBucket: 'codepriest-portfolio-92faf.firebasestorage.app',
    measurementId: 'G-DGMJBQ2WL2',
  );
}
